import { InputObjectType } from "../../types/InputObjectType";

export const StudentFormFields: InputObjectType[] = [
  {
    id: "name",
    placeholder: "Name",
    type: "text",
    label: "Name",
    error: [],
    value: "",
  },
  {
    id: "address",
    placeholder: "Address",
    type: "text",
    label: "Address",
    error: [],
    value: "",
  },
  {
    id: "phone",
    placeholder: "Phone",
    type: "text",
    label: "Phone",
    error: [],
    value: "",
  },
  {
    id: "email",
    placeholder: "Email",
    type: "text",
    label: "Email",
    error: [],
    value: "",
  },
  {
    id: "linkedin",
    placeholder: "LinkedIn",
    type: "text",
    label: "LinkedIn",
    error: [],
    value: "",
  },
  {
    id: "resume_link",
    placeholder: "Resume Link",
    type: "text",
    label: "Resume Link",
    error: [],
    value: "",
  },
  {
    id: "lca_cert",
    type: "checkbox",
    label: "LCA Certification",
    error: [],
    value: false,
    placeholder: "",
  },
  {
    id: "epa_608_cert",
    type: "checkbox",
    label: "EPA 608 Certification",
    error: [],
    value: false,
    placeholder: "",
  },
  {
    id: "s_j_cert",
    type: "checkbox",
    label: "S&J Cert",
    error: [],
    value: false,
    placeholder: "",
  },
  {
    id: "class_site",
    placeholder: "Class Site",
    type: "text",
    label: "Class Site",
    error: [],
    value: "",
  },
  {
    id: "class_number",
    placeholder: "Class Number",
    type: "text",
    label: "Class Number",
    error: [],
    value: "",
  },
  {
    id: "class_date",
    placeholder: "Class Date",
    type: "text",
    label: "Class Date",
    error: [],
    value: "",
  },
];
