import { InputObjectType } from "../types/InputObjectType";

export const StudentFormFields: InputObjectType[] = [
  {
    id: "name",
    placeholder: "Name",
    type: "text",
    label: "Name",
    error: [],
    value: "",
  },
  {
    id: "phone",
    placeholder: "Phone",
    type: "text",
    label: "Phone",
    error: [],
    value: "",
  },
  {
    id: "email",
    placeholder: "Email",
    type: "text",
    label: "Email",
    error: [],
    value: "",
  },
  {
    id: "address",
    placeholder: "Address",
    type: "text",
    label: "Address",
    error: [],
    value: "",
  },
  {
    id: "linkedin",
    placeholder: "LinkedIn",
    type: "text",
    label: "LinkedIn",
    error: [],
    value: "",
  },
  {
    id: "resume_link",
    placeholder: "Resume Link",
    type: "text",
    label: "Resume Link",
    error: [],
    value: "",
  },
  {
    id: "lca_cert",
    type: "checkbox",
    label: "LCA Certification",
    error: [],
    value: false,
    placeholder: "",
  },
  {
    id: "epa_608_cert",
    type: "checkbox",
    label: "EPA 608 Certification",
    error: [],
    value: false,
    placeholder: "",
  },
  {
    id: "s_j_cert",
    type: "checkbox",
    label: "S&J Cert",
    error: [],
    value: false,
    placeholder: "",
  },
  {
    id: "osha_30_10_cert",
    type: "checkbox",
    label: "OSHA 30/10 Cert",
    error: [],
    value: false,
    placeholder: "",
  },
  {
    id: "drivers_license",
    type: "checkbox",
    label: "Driver's License",
    error: [],
    value: false,
    placeholder: "",
  },
  {
    id: "hired",
    type: "checkbox",
    label: "Hired",
    error: [],
    value: false,
    placeholder: "",
  },
  {
    id: "notes",
    type: "textarea",
    label: "Notes",
    error: [],
    value: "",
    placeholder: "",
  },
];
