# Generated by Django 4.2.3 on 2023-08-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('website', models.URLField()),
                ('instagram', models.URLField()),
                ('tiktok', models.URLField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('donors', models.ManyToManyField(to='s_and_j_track.donor')),
                ('students', models.ManyToManyField(to='s_and_j_track.student')),
                ('visitors', models.ManyToManyField(to='s_and_j_track.employer')),
            ],
        ),
    ]
