name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: stacks_and_joules
          export_default_credentials: true

      - name: Deploy Django API
        run: |
        gcloud compute ssh instance-1 --zone=us-central1-a --command="cd /path/to/your/project && git pull origin main"

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Cloud Storage
        run: |
          gsutil cp -r dist/* gs://YOUR_BUCKET_NAME/
