import { InputObjectType } from "../../types/InputObjectType";

export const EmployerFormFields: InputObjectType[] = [
  {
    id: "name",
    placeholder: "Name",
    type: "text",
    label: "Name",
    error: [],
    value: "",
  },
  {
    id: "address",
    placeholder: "Address",
    type: "text",
    label: "Address",
    error: [],
    value: "",
  },
  {
    id: "primary_contact",
    placeholder: "Primary Contact",
    type: "text",
    label: "Primary Contact",
    error: [],
    value: "",
  },
  {
    id: "phone",
    placeholder: "Phone",
    type: "text",
    label: "Phone",
    error: [],
    value: "",
  },
  {
    id: "email",
    placeholder: "Email",
    type: "text",
    label: "Email",
    error: [],
    value: "",
  },
  {
    id: "website",
    placeholder: "Website",
    type: "text",
    label: "Website",
    error: [],
    value: "",
  },
  {
    id: "linkedin",
    placeholder: "Linkedin",
    type: "text",
    label: "Linkedin",
    error: [],
    value: "",
  },
  {
    id: "job_listings",
    placeholder: "Job Listings",
    type: "text",
    label: "Job Listings",
    error: [],
    value: "",
  },
  {
    id: "company_size",
    placeholder: "Company Size",
    type: "number",
    label: "Company Size",
    error: [],
    value: "",
  },
  {
    id: "speciality",
    placeholder: "Speciality",
    type: "text",
    label: "Speciality",
    error: [],
    value: "",
  },
];
