# Generated by Django 4.2.3 on 2024-03-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0002_instructor_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='donors',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='visitors',
        ),
        migrations.AddField(
            model_name='cohort',
            name='instructors',
            field=models.ManyToManyField(to='s_and_j_track.instructor'),
        ),
    ]
