# Generated by Django 4.2.3 on 2024-03-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0003_remove_cohort_donors_remove_cohort_visitors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
