# Generated by Django 4.2.3 on 2024-03-25 20:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0004_cohort_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='students',
        ),
        migrations.AddField(
            model_name='instructor',
            name='cohorts',
            field=models.ManyToManyField(related_name='instructors', to='s_and_j_track.cohort'),
        ),
        migrations.AddField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='s_and_j_track.cohort'),

            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
