# Generated by Django 4.2.3 on 2024-03-25 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0006_rename_end_date_cohort_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(default='2024-03-25'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='s_and_j_track.cohort'),
        ),
    ]
