# Generated by Django 4.2.3 on 2024-03-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0007_cohort_end_date_alter_student_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='s_and_j_track.cohort'),
            preserve_default=False,
        ),
    ]
