# Generated by Django 4.2.3 on 2024-03-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0008_donor_notes_student_notes_alter_student_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='instructors',
            field=models.ManyToManyField(related_name='assigned_cohorts', to='s_and_j_track.instructor'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='cohorts',
            field=models.ManyToManyField(related_name='assigned_instructors', to='s_and_j_track.cohort'),
        ),
    ]
