# Generated by Django 4.2.3 on 2024-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0009_cohort_instructors_alter_instructor_cohorts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='cohorts',
        ),
        migrations.AlterField(
            model_name='cohort',
            name='instructors',
            field=models.ManyToManyField(related_name='cohorts', to='s_and_j_track.instructor'),
        ),
    ]
