# Generated by Django 4.2.3 on 2024-04-04 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0013_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='s_and_j_track.organization'),
        ),
    ]
