# Generated by Django 4.2.3 on 2024-04-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0017_cohort_organization_donor_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_site',
        ),
        migrations.AddField(
            model_name='student',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s_and_j_track.employer'),
        ),
        migrations.AddField(
            model_name='student',
            name='hired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume_link',
            field=models.URLField(blank=True),
        ),
    ]
