# Generated by Django 4.2.3 on 2024-04-11 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0020_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='primary_contact',
        ),
    ]
