# Generated by Django 4.2.3 on 2024-05-02 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_and_j_track', '0021_remove_contact_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='osha_30_10_cert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='s_and_j_track.cohort'),
        ),
    ]
