name: Deploy to Multiple Google Cloud Projects

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/66681826221/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "paulgasbarra@stacks-and-joules-dev.iam.gserviceaccount.com"

      - name: Upload build assets to GCS
        run: |
          gsutil -m cp -r frontend/dist/* gs://stacks-and-joules-fe-dev/
