name: Deploy Vite App to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: List build output
        run: |
          cd frontend
          ls -al dist
          ls -al dist/assets

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: stacks-and-joules-frontend-dev
          service_account_key: ${{ secrets.S_AND_J_GCP_KEY }}
          export_default_credentials: true

      - name: Upload to GCS
        run: |
          gsutil -m cp -r frontend/dist gs://stacks-and-joules-frontend-dev/

      - name: Print site URL
        run: |
          echo "Check the deployed site at: https://storage.googleapis.com/stacks-and-joules-frontend-dev/index.html"
