name: Deploy to Multiple Google Cloud Projects

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/66681826221/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "paulgasbarra@stacks-and-joules-dev.iam.gserviceaccount.com"
        with:
          args: app deploy app.yaml

    # - name: Set up Cloud SDK for Backend
    #   uses: google-github-actions/setup-gcloud@v1
    #   with:
    #     project_id: stacks-and-joules
    #     version: latest

    # - name: Activate Service Account
    #   run: gcloud auth activate-service-account --key-file=- <<<"${{ secrets.GCP_SA_KEY }}"

    # - name: Get gcloud config
    #   run: gcloud config list

    # - name: Deploy backend to GAE in Project B
    #   run: |
    #     cd backend
    #     gcloud app deploy
