name: Deploy to Multiple Google Cloud Projects

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCP authentication
        run: printf '%s\n' "${{ secrets.GCP_SA_KEY }}" > service-account.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Display service-account.json
        run: cat service-account.json

      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=service-account.json

      # - name: Set up Cloud SDK for Backend
      #   uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     project_id: stacks-and-joules
      #     version: latest

      # - name: Activate Service Account
      #   run: gcloud auth activate-service-account --key-file=- <<<"${{ secrets.GCP_SA_KEY }}"

      # - name: Get gcloud config
      #   run: gcloud config list

      # - name: Deploy backend to GAE in Project B
      #   run: |
      #     cd backend
      #     gcloud app deploy
