name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "guildcache" #Must be unique in Heroku
          heroku_email: "paulgasbarra@gmail.com"
          appdir: "backend"
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Login to Heroku
        run: heroku login --apikey ${{secrets.HEROKU_API_KEY}}
      - name: Restart Heroku app
        run: heroku restart --app guildcache
